version: '3'
services:
  undetected-chromedriver:
    build: .
    image: undetected-chromedriver
    container_name: undetected-chromedriver
    command: python start.py
    entrypoint: /entrypoint.sh
    shm_size: '2gb'
    volumes:
      - ./mount:/opt/wd
    ports:
      - "5900:5900"
    environment:
      - VNC_PASSWORD=123456
